#ifndef __EVENT_LIST_DEF_H__
#define __EVENT_LIST_DEF_H__

#define DISPATCH_EVENT_TIMER_UPDATE         0
#define DISPATCH_EVENT_STEPPER_COMPLETE     1
#define DISPATCH_EVENT_TIMER_TICK           2
#define DISPATCH_EVENT_USB_CLI_RX           3

#endif //!__EVENT_LIST_DEF_H__
